// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQDLg_c4FE5B4L0aFzCAlLUNeKeuQIhH4',
    appId: '1:64013161717:web:efdb5154ef1771e31d21bc',
    messagingSenderId: '64013161717',
    projectId: 'twitter-clone-tobe1315',
    authDomain: 'twitter-clone-tobe1315.firebaseapp.com',
    storageBucket: 'twitter-clone-tobe1315.appspot.com',
    measurementId: 'G-VKXXENYKK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSH50mlNDjLSfTOHP97SVFYD6ssjvfjUs',
    appId: '1:64013161717:android:1b1c02fcfac780491d21bc',
    messagingSenderId: '64013161717',
    projectId: 'twitter-clone-tobe1315',
    storageBucket: 'twitter-clone-tobe1315.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfPv-fr_OEBly98bFDuifCV0LXHqYA2-I',
    appId: '1:64013161717:ios:f72759eed6c1ebe61d21bc',
    messagingSenderId: '64013161717',
    projectId: 'twitter-clone-tobe1315',
    storageBucket: 'twitter-clone-tobe1315.appspot.com',
    iosBundleId: 'com.example.tictokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfPv-fr_OEBly98bFDuifCV0LXHqYA2-I',
    appId: '1:64013161717:ios:f72759eed6c1ebe61d21bc',
    messagingSenderId: '64013161717',
    projectId: 'twitter-clone-tobe1315',
    storageBucket: 'twitter-clone-tobe1315.appspot.com',
    iosBundleId: 'com.example.tictokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQDLg_c4FE5B4L0aFzCAlLUNeKeuQIhH4',
    appId: '1:64013161717:web:ffa71a325b7f89dc1d21bc',
    messagingSenderId: '64013161717',
    projectId: 'twitter-clone-tobe1315',
    authDomain: 'twitter-clone-tobe1315.firebaseapp.com',
    storageBucket: 'twitter-clone-tobe1315.appspot.com',
    measurementId: 'G-51EBHNGHR6',
  );

}