// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtEd8Jnrf5UqAusnWw0KlSERg67x6TRVI',
    appId: '1:202047641107:web:e4428cd6f3ff5c5c84d1e6',
    messagingSenderId: '202047641107',
    projectId: 'twitter-clone-tobe13155131',
    authDomain: 'twitter-clone-tobe13155131.firebaseapp.com',
    storageBucket: 'twitter-clone-tobe13155131.appspot.com',
    measurementId: 'G-P6DHJME6R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_8yJYVmf8gRzSEmtC700dkSjpthVcnPs',
    appId: '1:202047641107:android:122d50eb7428103184d1e6',
    messagingSenderId: '202047641107',
    projectId: 'twitter-clone-tobe13155131',
    storageBucket: 'twitter-clone-tobe13155131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFPlTv8K_Wt_Rm3kROC9OyJa86KAzCF1U',
    appId: '1:202047641107:ios:05359ac89c403d3e84d1e6',
    messagingSenderId: '202047641107',
    projectId: 'twitter-clone-tobe13155131',
    storageBucket: 'twitter-clone-tobe13155131.appspot.com',
    iosBundleId: 'com.example.tictokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFPlTv8K_Wt_Rm3kROC9OyJa86KAzCF1U',
    appId: '1:202047641107:ios:05359ac89c403d3e84d1e6',
    messagingSenderId: '202047641107',
    projectId: 'twitter-clone-tobe13155131',
    storageBucket: 'twitter-clone-tobe13155131.appspot.com',
    iosBundleId: 'com.example.tictokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtEd8Jnrf5UqAusnWw0KlSERg67x6TRVI',
    appId: '1:202047641107:web:a97cf057071a466084d1e6',
    messagingSenderId: '202047641107',
    projectId: 'twitter-clone-tobe13155131',
    authDomain: 'twitter-clone-tobe13155131.firebaseapp.com',
    storageBucket: 'twitter-clone-tobe13155131.appspot.com',
    measurementId: 'G-FC0DBZ205H',
  );

}